// ─────────────────────────────────────────────────────────────
// Purchase Report Config — mirrors the Sales config, reusing the shared
// SalesReportDef shape, column formatters and the generic report-detail engine.
// Field names are the REAL Purchase response keys (verified against the backend
// PurchaseRegisterView): vendor_name, supplier_invoice_no, voucher, etc.
// ─────────────────────────────────────────────────────────────

import {
  SalesReportDef,
  cur, dt, qty, statusBadge,
} from '../sales-reports/sales-report-config';

// ─── Register-type column sets (per the 13 Purchase Register views) ───────────
export const PURCHASE_REGISTER_TYPE_COLS: Record<string, any[]> = {
  general: [
    { fieldKey: 'invoice_no',          name: 'Invoice No',     sort: true },
    { fieldKey: 'invoice_date',        name: 'Date',           sort: true,  displayType: 'map', mapFn: dt },
    { fieldKey: 'supplier_invoice_no', name: 'Supplier Inv',   sort: false },
    { fieldKey: 'vendor_name',         name: 'Vendor',         sort: true },
    { fieldKey: 'voucher',             name: 'Voucher',        sort: false },
    { fieldKey: 'total_amount',        name: 'Net Amount',     sort: true,  displayType: 'map', mapFn: cur },
    { fieldKey: 'paid_amount',         name: 'Paid',           sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'pending_amount',      name: 'Pending',        sort: true,  displayType: 'map', mapFn: cur },
    { fieldKey: 'status',              name: 'Status',         sort: false, displayType: 'map', mapFn: statusBadge },
    { fieldKey: 'due_date',            name: 'Due Date',       sort: true,  displayType: 'map', mapFn: dt },
    // ── secondary (hidden, available via Columns picker) ──
    { fieldKey: 'item_value',  name: 'Gross Amount', sort: true,  displayType: 'map', mapFn: cur, hidden: true },
    { fieldKey: 'dis_amt',     name: 'Discount',     sort: false, displayType: 'map', mapFn: cur, hidden: true },
    { fieldKey: 'tax_amount',  name: 'Tax',          sort: false, displayType: 'map', mapFn: cur, hidden: true },
    { fieldKey: 'round_off',   name: 'Round Off',    sort: false, displayType: 'map', mapFn: (v: any) => v != null && Number(v) !== 0 ? cur(v) : '—', hidden: true },
    { fieldKey: 'city',        name: 'City',         sort: false, displayType: 'map', mapFn: (v: any) => v || '—', hidden: true },
    { fieldKey: 'vendor_agent', name: 'Agent',       sort: false, displayType: 'map', mapFn: (v: any) => v || '—', hidden: true },
  ],
  detailed: [
    { fieldKey: 'invoice_no',   name: 'Invoice No', sort: true },
    { fieldKey: 'invoice_date', name: 'Date',       sort: true, displayType: 'map', mapFn: dt },
    { fieldKey: 'vendor_name',  name: 'Vendor',     sort: true },
    { fieldKey: 'product_name', name: 'Product',    sort: true },
    { fieldKey: 'product_code', name: 'Code',       sort: false },
    { fieldKey: 'hsn_code',     name: 'HSN',        sort: false },
    { fieldKey: 'unit',         name: 'Unit',       sort: false },
    { fieldKey: 'quantity',     name: 'Qty',        sort: true, displayType: 'map', mapFn: qty },
    { fieldKey: 'rate',         name: 'Rate',       sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'amount',       name: 'Amount',     sort: true, displayType: 'map', mapFn: cur },
    { fieldKey: 'discount',     name: 'Discount',   sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'cgst',         name: 'CGST',       sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'sgst',         name: 'SGST',       sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'igst',         name: 'IGST',       sort: false, displayType: 'map', mapFn: cur },
  ],
  columnar_tax_wise: [
    { fieldKey: 'invoice_no',     name: 'Invoice No', sort: true },
    { fieldKey: 'invoice_date',   name: 'Date',       sort: true, displayType: 'map', mapFn: dt },
    { fieldKey: 'vendor_name',    name: 'Vendor',     sort: true },
    { fieldKey: 'taxable_amount', name: 'Taxable',    sort: true, displayType: 'map', mapFn: cur },
    { fieldKey: 'cgst',           name: 'CGST',       sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'sgst',           name: 'SGST',       sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'igst',           name: 'IGST',       sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'total_tax',      name: 'Total Tax',  sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'net_amount',     name: 'Net Amount', sort: true, displayType: 'map', mapFn: cur },
  ],
  columnar_product_group: [
    { fieldKey: 'group_name',     name: 'Product Group', sort: true },
    { fieldKey: 'total_qty',      name: 'Total Qty',     sort: true, displayType: 'map', mapFn: qty },
    { fieldKey: 'gross_amount',   name: 'Gross Amount',  sort: true, displayType: 'map', mapFn: cur },
    { fieldKey: 'total_discount', name: 'Discount',      sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'cgst',           name: 'CGST',          sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'sgst',           name: 'SGST',          sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'igst',           name: 'IGST',          sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'net_amount',     name: 'Net Amount',    sort: true, displayType: 'map', mapFn: cur },
  ],
  columnar_product_category: [
    { fieldKey: 'group_name',     name: 'Category',     sort: true },
    { fieldKey: 'total_qty',      name: 'Total Qty',    sort: true, displayType: 'map', mapFn: qty },
    { fieldKey: 'gross_amount',   name: 'Gross Amount', sort: true, displayType: 'map', mapFn: cur },
    { fieldKey: 'total_discount', name: 'Discount',     sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'cgst',           name: 'CGST',         sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'sgst',           name: 'SGST',         sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'igst',           name: 'IGST',         sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'net_amount',     name: 'Net Amount',   sort: true, displayType: 'map', mapFn: cur },
  ],
  columnar_product_brand: [
    { fieldKey: 'group_name',     name: 'Brand',        sort: true },
    { fieldKey: 'total_qty',      name: 'Total Qty',    sort: true, displayType: 'map', mapFn: qty },
    { fieldKey: 'gross_amount',   name: 'Gross Amount', sort: true, displayType: 'map', mapFn: cur },
    { fieldKey: 'total_discount', name: 'Discount',     sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'net_amount',     name: 'Net Amount',   sort: true, displayType: 'map', mapFn: cur },
  ],
  columnar_hsn_wise: [
    { fieldKey: 'group_name',     name: 'HSN Code',      sort: true },
    { fieldKey: 'total_qty',      name: 'Total Qty',     sort: true, displayType: 'map', mapFn: qty },
    { fieldKey: 'gross_amount',   name: 'Taxable Value', sort: true, displayType: 'map', mapFn: cur },
    { fieldKey: 'total_discount', name: 'Discount',      sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'cgst',           name: 'CGST',          sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'sgst',           name: 'SGST',          sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'igst',           name: 'IGST',          sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'net_amount',     name: 'Net Amount',    sort: true, displayType: 'map', mapFn: cur },
  ],
  cancelled: [
    { fieldKey: 'invoice_no',   name: 'Invoice No', sort: true },
    { fieldKey: 'invoice_date', name: 'Date',       sort: true, displayType: 'map', mapFn: dt },
    { fieldKey: 'voucher',      name: 'Voucher',    sort: false },
    { fieldKey: 'vendor_name',  name: 'Vendor',     sort: true },
    { fieldKey: 'total_amount', name: 'Amount',     sort: true, displayType: 'map', mapFn: cur },
    { fieldKey: 'status',       name: 'Status',     sort: false },
  ],
  daily_summary: [
    { fieldKey: 'date',           name: 'Date',         sort: true, displayType: 'map', mapFn: dt },
    { fieldKey: 'invoice_count',  name: 'Invoices',     sort: true },
    { fieldKey: 'gross_amount',   name: 'Gross Amount', sort: true, displayType: 'map', mapFn: cur },
    { fieldKey: 'total_discount', name: 'Discount',     sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'tax_amount',     name: 'Tax',          sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'net_amount',     name: 'Net Amount',   sort: true, displayType: 'map', mapFn: cur },
  ],
  daily_payment_summary: [
    { fieldKey: 'date',          name: 'Date',         sort: true, displayType: 'map', mapFn: dt },
    { fieldKey: 'invoice_count', name: 'Invoices',     sort: true },
    { fieldKey: 'total_billed',  name: 'Total Billed', sort: true, displayType: 'map', mapFn: cur },
    { fieldKey: 'total_paid',    name: 'Paid',         sort: true, displayType: 'map', mapFn: cur },
    { fieldKey: 'total_pending', name: 'Pending',      sort: true, displayType: 'map', mapFn: cur },
  ],
  daily_tax_analysis: [
    { fieldKey: 'date',           name: 'Date',      sort: true, displayType: 'map', mapFn: dt },
    { fieldKey: 'taxable_amount', name: 'Taxable',   sort: true, displayType: 'map', mapFn: cur },
    { fieldKey: 'cgst',           name: 'CGST',      sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'sgst',           name: 'SGST',      sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'igst',           name: 'IGST',      sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'total_tax',      name: 'Total Tax', sort: false, displayType: 'map', mapFn: cur },
  ],
  monthly_summary: [
    { fieldKey: 'month',          name: 'Month',        sort: true },
    { fieldKey: 'invoice_count',  name: 'Invoices',     sort: true },
    { fieldKey: 'gross_amount',   name: 'Gross Amount', sort: true, displayType: 'map', mapFn: cur },
    { fieldKey: 'total_discount', name: 'Discount',     sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'tax_amount',     name: 'Tax',          sort: false, displayType: 'map', mapFn: cur },
    { fieldKey: 'net_amount',     name: 'Net Amount',   sort: true, displayType: 'map', mapFn: cur },
  ],
  monthly_payment_summary: [
    { fieldKey: 'month',         name: 'Month',        sort: true },
    { fieldKey: 'invoice_count', name: 'Invoices',     sort: true },
    { fieldKey: 'total_billed',  name: 'Total Billed', sort: true, displayType: 'map', mapFn: cur },
    { fieldKey: 'total_paid',    name: 'Paid',         sort: true, displayType: 'map', mapFn: cur },
    { fieldKey: 'total_pending', name: 'Pending',      sort: true, displayType: 'map', mapFn: cur },
  ],
};

export const PURCHASE_REGISTER_TYPE_GLOBAL_SEARCH: Record<string, string[]> = {
  general:                   ['invoice_no', 'supplier_invoice_no', 'vendor_name', 'voucher', 'status'],
  detailed:                  ['invoice_no', 'vendor_name', 'product_name', 'product_code', 'hsn_code', 'unit'],
  columnar_tax_wise:         ['invoice_no', 'vendor_name'],
  columnar_product_group:    ['group_name'],
  columnar_product_category: ['group_name'],
  columnar_product_brand:    ['group_name'],
  columnar_hsn_wise:         ['group_name'],
  cancelled:                 ['invoice_no', 'vendor_name', 'voucher', 'status'],
  daily_summary:             ['date'],
  daily_payment_summary:     ['date'],
  daily_tax_analysis:        ['date'],
  monthly_summary:           ['month'],
  monthly_payment_summary:   ['month'],
};

export const PURCHASE_REGISTER_TYPES = [
  { value: 'general',                   label: 'General Register' },
  { value: 'detailed',                  label: 'Detailed Register' },
  { value: 'columnar_tax_wise',         label: 'Columnar — Tax Wise' },
  { value: 'columnar_product_group',    label: 'Columnar — Product Group' },
  { value: 'columnar_product_category', label: 'Columnar — Product Category' },
  { value: 'columnar_product_brand',    label: 'Columnar — Brand Wise' },
  { value: 'columnar_hsn_wise',         label: 'Columnar — HSN Code Wise' },
  { value: 'cancelled',                 label: 'Cancelled Voucher List' },
  { value: 'daily_summary',             label: 'Daily Purchase Summary' },
  { value: 'daily_payment_summary',     label: 'Daily Payment Summary' },
  { value: 'daily_tax_analysis',        label: 'Daily Tax Analysis' },
  { value: 'monthly_summary',           label: 'Monthly Purchase Summary' },
  { value: 'monthly_payment_summary',   label: 'Monthly Payment Summary' },
];

// ─── Purchase report definitions (reuse the SalesReportDef shape) ─────────────
export const PURCHASE_REPORTS: SalesReportDef[] = [
  {
    key: 'purchase_register',
    name: 'Purchase Register',
    description: 'Invoice-level purchase register — 13 view types including daily, monthly, tax & columnar',
    category: 'Sale Register', // category is only used by the legacy sales hub; unused here
    apiUrl: 'reports/purchase/register/',
    reportType: 'Detailed',
    pkId: 'purchase_invoice_id',
    cols: PURCHASE_REGISTER_TYPE_COLS['general'],
    globalSearch: { keys: PURCHASE_REGISTER_TYPE_GLOBAL_SEARCH['general'] },
    defaultSort: { key: 'invoice_date', value: 'descend' },
    filters: ['dateRange', 'period', 'registerType', 'search'],
    // Lean bar (Vendor only) so the toolbar never overflows under the sidebar.
    barFilters: ['vendor'],
    moreFilters: ['voucher', 'status', 'city', 'minAmount', 'maxAmount'],
    registerTypes: PURCHASE_REGISTER_TYPES,
    registerCols: PURCHASE_REGISTER_TYPE_COLS,
    registerGlobalSearch: PURCHASE_REGISTER_TYPE_GLOBAL_SEARCH,
    showSummaryStrip: true,
  },

  // ── Pending Purchase Orders ──────────────────────────────────
  {
    key: 'pending_purchase_orders',
    name: 'Pending Purchase Orders',
    description: 'Purchase orders not yet completed',
    category: 'Sale Register',
    apiUrl: 'reports/purchase/pending-orders/',
    reportType: 'Summary',
    pkId: 'purchase_order_id',
    cols: [
      { fieldKey: 'order_no',      name: 'Order No',     sort: true },
      { fieldKey: 'order_date',    name: 'Order Date',   sort: true, displayType: 'map', mapFn: dt },
      { fieldKey: 'delivery_date', name: 'Delivery',     sort: true, displayType: 'map', mapFn: dt },
      { fieldKey: 'vendor_name',   name: 'Vendor',       sort: true },
      { fieldKey: 'purchase_type', name: 'Type',         sort: false },
      { fieldKey: 'order_status',  name: 'Status',       sort: false },
      { fieldKey: 'item_value',    name: 'Item Value',   sort: true, displayType: 'map', mapFn: cur },
      { fieldKey: 'tax_amount',    name: 'Tax',          sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'total_amount',  name: 'Total',        sort: true, displayType: 'map', mapFn: cur },
    ],
    globalSearch: { keys: ['order_no', 'vendor_name', 'purchase_type', 'order_status'] },
    defaultSort: { key: 'order_date', value: 'descend' },
    filters: ['dateRange', 'period', 'search'],
    barFilters: ['vendor', 'status'],
  },

  // ── Purchase Order Register ──────────────────────────────────
  {
    key: 'purchase_order_register',
    name: 'Purchase Order Register',
    description: 'All purchase orders with status and value',
    category: 'Sale Register',
    apiUrl: 'reports/purchase/order-register/',
    reportType: 'Detailed',
    pkId: 'purchase_order_id',
    cols: [
      { fieldKey: 'order_no',      name: 'Order No',   sort: true },
      { fieldKey: 'order_date',    name: 'Date',       sort: true, displayType: 'map', mapFn: dt },
      { fieldKey: 'delivery_date', name: 'Delivery',   sort: true, displayType: 'map', mapFn: dt },
      { fieldKey: 'vendor_name',   name: 'Vendor',     sort: true },
      { fieldKey: 'purchase_type', name: 'Type',       sort: false },
      { fieldKey: 'order_status',  name: 'Status',     sort: false },
      { fieldKey: 'item_value',    name: 'Item Value', sort: true, displayType: 'map', mapFn: cur },
      { fieldKey: 'tax_amount',    name: 'Tax',        sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'total_amount',  name: 'Total',      sort: true, displayType: 'map', mapFn: cur },
    ],
    globalSearch: { keys: ['order_no', 'vendor_name', 'purchase_type', 'order_status'] },
    defaultSort: { key: 'order_date', value: 'descend' },
    filters: ['dateRange', 'period', 'search', 'minAmount', 'maxAmount'],
    barFilters: ['vendor', 'status'],
    moreFilters: ['minAmount', 'maxAmount'],
  },

  // ── Purchase Return Register ─────────────────────────────────
  {
    key: 'purchase_return_register',
    name: 'Purchase Return Register',
    description: 'All purchase returns with reason and value',
    category: 'Sale Register',
    apiUrl: 'reports/purchase/return-register/',
    reportType: 'Detailed',
    pkId: 'purchase_return_id',
    cols: [
      { fieldKey: 'return_no',      name: 'Return No',  sort: true },
      { fieldKey: 'return_date',    name: 'Date',       sort: true, displayType: 'map', mapFn: dt },
      { fieldKey: 'vendor_name',    name: 'Vendor',     sort: true },
      { fieldKey: 'ref_no',         name: 'Ref No',     sort: false },
      { fieldKey: 'return_reason',  name: 'Reason',     sort: false },
      { fieldKey: 'item_value',     name: 'Item Value', sort: true, displayType: 'map', mapFn: cur },
      { fieldKey: 'tax_amount',     name: 'Tax',        sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'total_amount',   name: 'Total',      sort: true, displayType: 'map', mapFn: cur },
      { fieldKey: 'order_status',   name: 'Status',     sort: false },
    ],
    globalSearch: { keys: ['return_no', 'vendor_name', 'ref_no', 'return_reason', 'order_status'] },
    defaultSort: { key: 'return_date', value: 'descend' },
    filters: ['dateRange', 'period', 'search'],
    barFilters: ['vendor', 'status'],
  },

  // ── Bill Payment Register ────────────────────────────────────
  {
    key: 'bill_payment_register',
    name: 'Bill Payment Register',
    description: 'All payments made to vendors',
    category: 'Sale Register',
    apiUrl: 'reports/purchase/bill-payments/',
    reportType: 'Detailed',
    pkId: 'transaction_id',
    cols: [
      { fieldKey: 'payment_receipt_no', name: 'Receipt No',  sort: true },
      { fieldKey: 'payment_date',       name: 'Date',        sort: true, displayType: 'map', mapFn: dt },
      { fieldKey: 'vendor_name',        name: 'Vendor',      sort: true },
      { fieldKey: 'invoice_no',         name: 'Invoice No',  sort: false },
      { fieldKey: 'bill_no',            name: 'Bill No',     sort: false },
      { fieldKey: 'payment_method',     name: 'Method',      sort: false },
      { fieldKey: 'amount',             name: 'Amount',      sort: true, displayType: 'map', mapFn: cur },
      { fieldKey: 'payment_status',     name: 'Status',      sort: false, displayType: 'map', mapFn: statusBadge },
    ],
    globalSearch: { keys: ['payment_receipt_no', 'vendor_name', 'bill_no', 'payment_method', 'payment_status'] },
    defaultSort: { key: 'payment_date', value: 'descend' },
    filters: ['dateRange', 'period', 'search'],
    barFilters: ['vendor'],
  },

  // ── Vendor Outstanding ───────────────────────────────────────
  {
    key: 'vendor_outstanding',
    name: 'Vendor Outstanding',
    description: 'Purchase invoices with pending payables and days overdue',
    category: 'Sale Register',
    apiUrl: 'reports/purchase/vendor-outstanding/',
    reportType: 'Summary',
    pkId: 'purchase_invoice_id',
    cols: [
      { fieldKey: 'invoice_no',     name: 'Invoice No',   sort: true },
      { fieldKey: 'invoice_date',   name: 'Invoice Date', sort: true, displayType: 'map', mapFn: dt },
      { fieldKey: 'due_date',       name: 'Due Date',     sort: true, displayType: 'map', mapFn: dt },
      { fieldKey: 'vendor_name',    name: 'Vendor',       sort: true },
      { fieldKey: 'total_amount',   name: 'Total',        sort: true, displayType: 'map', mapFn: cur },
      { fieldKey: 'paid_amount',    name: 'Paid',         sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'pending_amount', name: 'Pending',      sort: true, displayType: 'map', mapFn: cur },
      { fieldKey: 'days_overdue',   name: 'Days Overdue', sort: true },
      { fieldKey: 'status',         name: 'Status',       sort: false, displayType: 'map', mapFn: statusBadge },
    ],
    globalSearch: { keys: ['invoice_no', 'vendor_name', 'status'] },
    defaultSort: { key: 'due_date', value: 'ascend' },
    filters: ['dateRange', 'period', 'search'],
    barFilters: ['vendor'],
    moreFilters: ['minPending'],
  },

  // ── Vendor Aging ─────────────────────────────────────────────
  {
    key: 'vendor_aging',
    name: 'Vendor Aging',
    description: 'Payables bucketed: Current, 1-30, 31-60, 61-90, 91-120, 120+ days',
    category: 'Sale Register',
    apiUrl: 'reports/purchase/vendor-aging/',
    reportType: 'Grouped',
    pkId: 'vendor_id',
    cols: [
      { fieldKey: 'vendor_name',       name: 'Vendor',           sort: true },
      { fieldKey: 'total_outstanding', name: 'Total Outstanding',sort: true, displayType: 'map', mapFn: cur },
      { fieldKey: 'current',           name: 'Current',          sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'days_1_30',         name: '1-30 Days',        sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'days_31_60',        name: '31-60 Days',       sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'days_61_90',        name: '61-90 Days',       sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'days_91_120',       name: '91-120 Days',      sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'days_120_plus',     name: '120+ Days',        sort: false, displayType: 'map', mapFn: cur },
    ],
    globalSearch: { keys: ['vendor_name'] },
    defaultSort: { key: 'total_outstanding', value: 'descend' },
    filters: ['asOfDate', 'search'],
    barFilters: ['vendor'],
  },

  // ── Purchase Analysis — Product ──────────────────────────────
  {
    key: 'purchase_analysis_product',
    name: 'Purchase Analysis — Product',
    description: 'Quantity bought, cost and tax per product',
    category: 'Sale Register',
    apiUrl: 'reports/purchase/analysis/product/',
    reportType: 'Grouped',
    pkId: 'product_id',
    cols: [
      { fieldKey: 'product_name',   name: 'Product',      sort: true },
      { fieldKey: 'product_code',   name: 'Code',         sort: false },
      { fieldKey: 'total_qty',      name: 'Total Qty',    sort: true, displayType: 'map', mapFn: qty },
      { fieldKey: 'gross_amount',   name: 'Gross Amount', sort: true, displayType: 'map', mapFn: cur },
      { fieldKey: 'total_discount', name: 'Discount',     sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'total_tax',      name: 'Tax',          sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'net_amount',     name: 'Net Amount',   sort: true, displayType: 'map', mapFn: cur },
      { fieldKey: 'avg_rate',       name: 'Avg Rate',     sort: false, displayType: 'map', mapFn: cur },
    ],
    globalSearch: { keys: ['product_name', 'product_code'] },
    defaultSort: { key: 'gross_amount', value: 'descend' },
    filters: ['dateRange', 'period', 'search'],
    barFilters: ['productGroup', 'productCategory', 'productBrand'],
  },

  // ── Purchase Analysis — Vendor ───────────────────────────────
  {
    key: 'purchase_analysis_vendor',
    name: 'Purchase Analysis — Vendor',
    description: 'Spend, paid and pending per vendor',
    category: 'Sale Register',
    apiUrl: 'reports/purchase/analysis/vendor/',
    reportType: 'Grouped',
    pkId: 'vendor_id',
    cols: [
      { fieldKey: 'vendor_name',       name: 'Vendor',       sort: true },
      { fieldKey: 'total_invoices',    name: 'Invoices',     sort: true },
      { fieldKey: 'total_amount',      name: 'Total Amount', sort: true, displayType: 'map', mapFn: cur },
      { fieldKey: 'total_paid',        name: 'Paid',         sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'total_pending',     name: 'Pending',      sort: true, displayType: 'map', mapFn: cur },
      { fieldKey: 'avg_invoice_value', name: 'Avg Invoice',  sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'last_invoice_date', name: 'Last Invoice', sort: true, displayType: 'map', mapFn: dt },
    ],
    globalSearch: { keys: ['vendor_name'] },
    defaultSort: { key: 'total_amount', value: 'descend' },
    filters: ['dateRange', 'period', 'search'],
    barFilters: ['vendor'],
  },

  // ── GST Input Summary ────────────────────────────────────────
  {
    key: 'gst_input_summary',
    name: 'GST Input Summary',
    description: 'Input tax credit (CGST/SGST/IGST) per purchase invoice',
    category: 'Sale Register',
    apiUrl: 'reports/purchase/tax/gst-input-summary/',
    reportType: 'Detailed',
    pkId: 'invoice_no',
    cols: [
      { fieldKey: 'invoice_no',     name: 'Invoice No', sort: true },
      { fieldKey: 'invoice_date',   name: 'Date',       sort: true, displayType: 'map', mapFn: dt },
      { fieldKey: 'vendor_name',    name: 'Vendor',     sort: true },
      { fieldKey: 'taxable_amount', name: 'Taxable',    sort: true, displayType: 'map', mapFn: cur },
      { fieldKey: 'cgst',           name: 'CGST',       sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'sgst',           name: 'SGST',       sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'igst',           name: 'IGST',       sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'total_tax',      name: 'Total Tax',  sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'net_amount',     name: 'Net Amount', sort: true, displayType: 'map', mapFn: cur },
    ],
    globalSearch: { keys: ['invoice_no', 'vendor_name'] },
    defaultSort: { key: 'invoice_date', value: 'descend' },
    filters: ['dateRange', 'period', 'search'],
    barFilters: ['vendor'],
  },

  // ── Purchase Price Variance (reuses the price_variance Smart Insight) ──
  {
    key: 'purchase_price_variance',
    name: 'Purchase Price Variance',
    description: 'Overspend vs the best available vendor rate, per product',
    category: 'Sale Register',
    apiUrl: 'reports/purchase/price-variance/',
    reportType: 'Grouped',
    pkId: 'product_id',
    cols: [
      { fieldKey: 'product_name',   name: 'Product',     sort: true },
      { fieldKey: 'product_code',   name: 'Code',        sort: false },
      { fieldKey: 'vendor_name',    name: 'Vendor',      sort: true },
      { fieldKey: 'avg_rate',       name: 'Your Rate',   sort: true, displayType: 'map', mapFn: cur },
      { fieldKey: 'best_rate',      name: 'Best Rate',   sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'overspend',      name: 'Overspend',   sort: true, displayType: 'map', mapFn: cur },
      { fieldKey: 'total_qty',      name: 'Qty',         sort: false, displayType: 'map', mapFn: qty },
      { fieldKey: 'purchase_count', name: 'Buys',        sort: false },
      { fieldKey: 'trend',          name: 'Price Trend', sort: false },
    ],
    globalSearch: { keys: ['product_name', 'product_code', 'vendor_name'] },
    defaultSort: { key: 'overspend', value: 'descend' },
    filters: ['dateRange', 'period', 'search'],
    summaryStrip: [
      { key: 'products_analyzed', label: 'Products' },
      { key: 'vendors_compared',  label: 'Vendors' },
      { key: 'total_overspend',   label: 'Total Overspend', currency: true },
    ],
  },

  // ── Stock Replenishment (reuses the auto_purchase_order Smart Insight) ──
  {
    key: 'stock_replenishment',
    name: 'Stock Replenishment',
    description: 'Items at/below reorder level needing a purchase, with best vendor',
    category: 'Sale Register',
    apiUrl: 'reports/purchase/stock-replenishment/',
    reportType: 'Summary',
    pkId: 'product_id',
    cols: [
      { fieldKey: 'product_name',     name: 'Product',     sort: true },
      { fieldKey: 'product_code',     name: 'Code',        sort: false },
      { fieldKey: 'current_balance',  name: 'Stock',       sort: true, displayType: 'map', mapFn: qty },
      { fieldKey: 'minimum_level',    name: 'Min Level',   sort: false, displayType: 'map', mapFn: qty },
      { fieldKey: 'reorder_qty',      name: 'Reorder Qty', sort: true, displayType: 'map', mapFn: qty },
      { fieldKey: 'best_vendor_name', name: 'Best Vendor', sort: false },
      { fieldKey: 'latest_rate',      name: 'Rate',        sort: false, displayType: 'map', mapFn: cur },
      { fieldKey: 'estimated_cost',   name: 'Est. Cost',   sort: true, displayType: 'map', mapFn: cur },
    ],
    globalSearch: { keys: ['product_name', 'product_code', 'best_vendor_name'] },
    defaultSort: { key: 'estimated_cost', value: 'descend' },
    filters: ['search'],
    showDateFilters: false,
    summaryStrip: [
      { key: 'total_items',          label: 'Items to Reorder' },
      { key: 'total_estimated_cost', label: 'Est. Cost', currency: true },
    ],
  },

  // ── Vendor Performance (reuses the best_vendor Smart Insight, per vendor) ──
  {
    key: 'vendor_performance',
    name: 'Vendor Performance',
    description: 'Price / delivery / quality scorecard per vendor',
    category: 'Sale Register',
    apiUrl: 'reports/purchase/vendor-performance/',
    reportType: 'Grouped',
    pkId: 'vendor_id',
    cols: [
      { fieldKey: 'vendor_name',       name: 'Vendor',     sort: true },
      { fieldKey: 'products_supplied', name: 'Products',   sort: true },
      { fieldKey: 'price_score',       name: 'Price',      sort: true, displayType: 'map', mapFn: (v: any) => v != null ? `${v}` : 'N/A' },
      { fieldKey: 'delivery_score',    name: 'Delivery',   sort: false, displayType: 'map', mapFn: (v: any) => v != null ? `${v}` : 'N/A' },
      { fieldKey: 'quality_score',     name: 'Quality',    sort: false, displayType: 'map', mapFn: (v: any) => v != null ? `${v}` : 'N/A' },
      { fieldKey: 'overall_score',     name: 'Overall',    sort: true, displayType: 'map', mapFn: (v: any) => v != null ? `${v}` : 'N/A' },
      { fieldKey: 'total_returns',     name: 'Returns Qty', sort: false, displayType: 'map', mapFn: qty },
    ],
    globalSearch: { keys: ['vendor_name'] },
    defaultSort: { key: 'overall_score', value: 'descend' },
    filters: ['search'],
    showDateFilters: false,
    summaryStrip: [
      { key: 'total_vendors', label: 'Vendors' },
    ],
  },
];
